# Change these first
owner: janparkio # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: TUPI
    url: https://tupi.com.py/
  - name: Nutrihuevos
    url: https://nutrihuevos.com.py/
  - name: YWAM Asunción
    url: https://ywamasuncion.com/
  - name: TAVA
    url: https://tava.com.py/
  - name: Finefoods
    url: https://finefoods.com.py/
  - name: Kimchi Club
    url: https://kimchiclub.com/
  - name: TIVE
    url: https://tive.com.py/

status-website:
#   Add your custom domain name, or remove the `cname` line if you don't have a domain
#   Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
#   cname: cname.url.com
  baseUrl: https://janparkio.github.io/uptime
  logoUrl: https://janparkio.github.io/client-tive/email-signatures/img/tive--logo.png
  name: Uptime tive
  introTitle: "**Uptime**"
  introMessage: "No server required"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/janparkio/uptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
